name: 'Rust Release Action'
description: 'Automate Rust project releases with changelog extraction, version validation, and cross-platform builds'
author: 'Michael Klishin'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  command:
    description: 'Command: extract-changelog, validate-version, get-version, release-linux, release-linux-deb, release-linux-rpm, release-linux-apk, release-macos, release-windows, release-windows-msi'
    required: true

  version:
    description: 'Version to extract (without v prefix)'
    required: false

  changelog:
    description: 'Path to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'

  output:
    description: 'Output file for release notes'
    required: false
    default: 'release_notes.md'

  tag:
    description: 'Git tag (defaults to GITHUB_REF_NAME)'
    required: false

  expected-version:
    description: 'Expected version (defaults to NEXT_RELEASE_VERSION variable)'
    required: false

  manifest:
    description: 'Path to Cargo.toml'
    required: false
    default: 'Cargo.toml'

  target:
    description: 'Rust target triple'
    required: false

  binary-name:
    description: 'Binary name (defaults to package name)'
    required: false

  package:
    description: 'Cargo package name for workspace builds'
    required: false

  no-default-features:
    description: 'Build with --no-default-features'
    required: false
    default: 'false'

  target-rustflags:
    description: 'Extra RUSTFLAGS for the build'
    required: false

  archive:
    description: 'Create archive (.tar.gz on Linux/macOS, .zip on Windows)'
    required: false
    default: 'false'

  locked:
    description: 'Build with --locked for reproducible builds'
    required: false
    default: 'false'

  features:
    description: 'Comma-separated list of Cargo features to enable'
    required: false

  include:
    description: 'Comma-separated glob patterns for additional files to include in archive'
    required: false

  checksum:
    description: 'Checksum algorithms to generate (sha256, sha512, b2)'
    required: false
    default: 'sha256'

  profile:
    description: 'Cargo build profile'
    required: false
    default: 'release'

  dry-run:
    description: 'Build without uploading (for testing)'
    required: false
    default: 'false'

  working-directory:
    description: 'Working directory for commands'
    required: false
    default: '.'

  pkg-description:
    description: 'Package description for .deb/.rpm'
    required: false

  pkg-maintainer:
    description: 'Package maintainer (format: Name <email>)'
    required: false

  pkg-homepage:
    description: 'Package homepage URL'
    required: false

  pkg-license:
    description: 'Package license (e.g., MIT, Apache-2.0)'
    required: false

  pkg-vendor:
    description: 'Package vendor name'
    required: false

  pkg-section:
    description: 'Debian package section (default: utils)'
    required: false
    default: 'utils'

  pkg-priority:
    description: 'Debian package priority (default: optional)'
    required: false
    default: 'optional'

  pkg-group:
    description: 'RPM package group (default: Applications/System)'
    required: false
    default: 'Applications/System'

  pkg-release:
    description: 'Package release/revision number (default: 1 for RPM, 0 for APK)'
    required: false

  pkg-depends:
    description: 'Comma-separated package dependencies'
    required: false

  pkg-recommends:
    description: 'Comma-separated recommended packages'
    required: false

  pkg-suggests:
    description: 'Comma-separated suggested packages'
    required: false

  pkg-conflicts:
    description: 'Comma-separated conflicting packages'
    required: false

  pkg-replaces:
    description: 'Comma-separated packages this replaces'
    required: false

  pkg-provides:
    description: 'Comma-separated virtual packages this provides'
    required: false

  pkg-contents:
    description: 'Extra files to include (format: src:dst,src:dst)'
    required: false

outputs:
  version:
    description: 'Version from get-version, validate-version, or release commands'
    value: ${{ steps.run.outputs.version }}

  release_notes_file:
    description: 'Path to release notes file'
    value: ${{ steps.run.outputs.release_notes_file }}

  release_notes:
    description: 'Release notes content'
    value: ${{ steps.run.outputs.release_notes }}

  artifact:
    description: 'Artifact filename'
    value: ${{ steps.run.outputs.artifact }}

  artifact_path:
    description: 'Full path to artifact'
    value: ${{ steps.run.outputs.artifact_path }}

  binary_name:
    description: 'Binary name that was built'
    value: ${{ steps.run.outputs.binary_name }}

  binary_path:
    description: 'Path to the raw binary (before archiving)'
    value: ${{ steps.run.outputs.binary_path }}

  target:
    description: 'Target triple used for the build'
    value: ${{ steps.run.outputs.target }}

  sha256:
    description: 'SHA256 checksum of the artifact'
    value: ${{ steps.run.outputs.sha256 }}

  sha512:
    description: 'SHA512 checksum of the artifact'
    value: ${{ steps.run.outputs.sha512 }}

  b2:
    description: 'BLAKE2 checksum of the artifact'
    value: ${{ steps.run.outputs.b2 }}

  summary:
    description: 'JSON summary of the build'
    value: ${{ steps.run.outputs.summary }}

runs:
  using: 'composite'
  steps:
    - name: Setup Nu shell
      # v3.17
      uses: hustcer/setup-nu@9e713eb2a9c4c5c7f7aa4278295684786bdfb280
      with:
        version: '0.110.0'

    - name: Run command
      id: run
      shell: nu {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        let scripts = $"($env.GITHUB_ACTION_PATH)/scripts"
        $env.NU_LIB_DIRS = [$scripts]

        match $"${{ inputs.command }}" {
            "extract-changelog" => {
                $env.VERSION = $"${{ inputs.version }}"
                $env.CHANGELOG_PATH = $"${{ inputs.changelog }}"
                $env.OUTPUT_PATH = $"${{ inputs.output }}"
                nu $"($scripts)/extract-changelog.nu"
            }
            "validate-version" => {
                $env.TAG = if "${{ inputs.tag }}" != "" { "${{ inputs.tag }}" } else { $env.GITHUB_REF_NAME? | default "" }
                $env.EXPECTED_VERSION = if "${{ inputs.expected-version }}" != "" { "${{ inputs.expected-version }}" } else { $env.NEXT_RELEASE_VERSION? | default "" }
                nu $"($scripts)/validate-version.nu"
            }
            "get-version" => {
                $env.MANIFEST_PATH = $"${{ inputs.manifest }}"
                nu $"($scripts)/get-version.nu"
            }
            "release-linux" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.include }}" != "" { $env.INCLUDE = "${{ inputs.include }}" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                nu $"($scripts)/release-linux.nu"
            }
            "release-linux-deb" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                if "${{ inputs.pkg-description }}" != "" { $env.PKG_DESCRIPTION = "${{ inputs.pkg-description }}" }
                if "${{ inputs.pkg-maintainer }}" != "" { $env.PKG_MAINTAINER = "${{ inputs.pkg-maintainer }}" }
                if "${{ inputs.pkg-homepage }}" != "" { $env.PKG_HOMEPAGE = "${{ inputs.pkg-homepage }}" }
                if "${{ inputs.pkg-license }}" != "" { $env.PKG_LICENSE = "${{ inputs.pkg-license }}" }
                if "${{ inputs.pkg-vendor }}" != "" { $env.PKG_VENDOR = "${{ inputs.pkg-vendor }}" }
                if "${{ inputs.pkg-section }}" != "" { $env.PKG_SECTION = "${{ inputs.pkg-section }}" }
                if "${{ inputs.pkg-priority }}" != "" { $env.PKG_PRIORITY = "${{ inputs.pkg-priority }}" }
                if "${{ inputs.pkg-depends }}" != "" { $env.PKG_DEPENDS = "${{ inputs.pkg-depends }}" }
                if "${{ inputs.pkg-recommends }}" != "" { $env.PKG_RECOMMENDS = "${{ inputs.pkg-recommends }}" }
                if "${{ inputs.pkg-suggests }}" != "" { $env.PKG_SUGGESTS = "${{ inputs.pkg-suggests }}" }
                if "${{ inputs.pkg-conflicts }}" != "" { $env.PKG_CONFLICTS = "${{ inputs.pkg-conflicts }}" }
                if "${{ inputs.pkg-replaces }}" != "" { $env.PKG_REPLACES = "${{ inputs.pkg-replaces }}" }
                if "${{ inputs.pkg-provides }}" != "" { $env.PKG_PROVIDES = "${{ inputs.pkg-provides }}" }
                if "${{ inputs.pkg-contents }}" != "" { $env.PKG_CONTENTS = "${{ inputs.pkg-contents }}" }
                nu $"($scripts)/release-linux-deb.nu"
            }
            "release-linux-rpm" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                if "${{ inputs.pkg-description }}" != "" { $env.PKG_DESCRIPTION = "${{ inputs.pkg-description }}" }
                if "${{ inputs.pkg-maintainer }}" != "" { $env.PKG_MAINTAINER = "${{ inputs.pkg-maintainer }}" }
                if "${{ inputs.pkg-homepage }}" != "" { $env.PKG_HOMEPAGE = "${{ inputs.pkg-homepage }}" }
                if "${{ inputs.pkg-license }}" != "" { $env.PKG_LICENSE = "${{ inputs.pkg-license }}" }
                if "${{ inputs.pkg-vendor }}" != "" { $env.PKG_VENDOR = "${{ inputs.pkg-vendor }}" }
                if "${{ inputs.pkg-group }}" != "" { $env.PKG_GROUP = "${{ inputs.pkg-group }}" }
                if "${{ inputs.pkg-release }}" != "" { $env.PKG_RELEASE = "${{ inputs.pkg-release }}" }
                if "${{ inputs.pkg-depends }}" != "" { $env.PKG_DEPENDS = "${{ inputs.pkg-depends }}" }
                if "${{ inputs.pkg-recommends }}" != "" { $env.PKG_RECOMMENDS = "${{ inputs.pkg-recommends }}" }
                if "${{ inputs.pkg-suggests }}" != "" { $env.PKG_SUGGESTS = "${{ inputs.pkg-suggests }}" }
                if "${{ inputs.pkg-conflicts }}" != "" { $env.PKG_CONFLICTS = "${{ inputs.pkg-conflicts }}" }
                if "${{ inputs.pkg-replaces }}" != "" { $env.PKG_REPLACES = "${{ inputs.pkg-replaces }}" }
                if "${{ inputs.pkg-provides }}" != "" { $env.PKG_PROVIDES = "${{ inputs.pkg-provides }}" }
                if "${{ inputs.pkg-contents }}" != "" { $env.PKG_CONTENTS = "${{ inputs.pkg-contents }}" }
                nu $"($scripts)/release-linux-rpm.nu"
            }
            "release-linux-apk" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                if "${{ inputs.pkg-description }}" != "" { $env.PKG_DESCRIPTION = "${{ inputs.pkg-description }}" }
                if "${{ inputs.pkg-maintainer }}" != "" { $env.PKG_MAINTAINER = "${{ inputs.pkg-maintainer }}" }
                if "${{ inputs.pkg-homepage }}" != "" { $env.PKG_HOMEPAGE = "${{ inputs.pkg-homepage }}" }
                if "${{ inputs.pkg-license }}" != "" { $env.PKG_LICENSE = "${{ inputs.pkg-license }}" }
                if "${{ inputs.pkg-vendor }}" != "" { $env.PKG_VENDOR = "${{ inputs.pkg-vendor }}" }
                if "${{ inputs.pkg-release }}" != "" { $env.PKG_RELEASE = "${{ inputs.pkg-release }}" }
                if "${{ inputs.pkg-depends }}" != "" { $env.PKG_DEPENDS = "${{ inputs.pkg-depends }}" }
                if "${{ inputs.pkg-conflicts }}" != "" { $env.PKG_CONFLICTS = "${{ inputs.pkg-conflicts }}" }
                if "${{ inputs.pkg-replaces }}" != "" { $env.PKG_REPLACES = "${{ inputs.pkg-replaces }}" }
                if "${{ inputs.pkg-provides }}" != "" { $env.PKG_PROVIDES = "${{ inputs.pkg-provides }}" }
                if "${{ inputs.pkg-contents }}" != "" { $env.PKG_CONTENTS = "${{ inputs.pkg-contents }}" }
                nu $"($scripts)/release-linux-apk.nu"
            }
            "release-macos" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.include }}" != "" { $env.INCLUDE = "${{ inputs.include }}" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                nu $"($scripts)/release-macos.nu"
            }
            "release-windows" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.include }}" != "" { $env.INCLUDE = "${{ inputs.include }}" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                nu $"($scripts)/release-windows.nu"
            }
            "release-windows-msi" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.features }}" != "" { $env.FEATURES = "${{ inputs.features }}" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.locked }}" == "true" { $env.LOCKED = "true" }
                if "${{ inputs.include }}" != "" { $env.INCLUDE = "${{ inputs.include }}" }
                if "${{ inputs.checksum }}" != "" { $env.CHECKSUM = "${{ inputs.checksum }}" }
                if "${{ inputs.profile }}" != "" { $env.PROFILE = "${{ inputs.profile }}" }
                nu $"($scripts)/release-windows-msi.nu"
            }
            _ => {
                print $"(ansi red)ERROR:(ansi reset) unknown command '${{ inputs.command }}'"
                exit 1
            }
        }
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        NEXT_RELEASE_VERSION: ${{ vars.NEXT_RELEASE_VERSION }}
